window.SUPPLY_DATA = {
  verifiedAt: "2026-07-30T08:30:00+08:00",
  markets: [
    {
      id: "brent",
      name: { zh: "布伦特原油现货", en: "Brent spot crude" },
      value: 86.99,
      unit: "USD/bbl",
      change: null,
      effectiveDate: "2026-07-20",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "U.S. EIA",
      sourceUrl: "https://www.eia.gov/dnav/pet/hist/RBRTED.htm",
      note: { zh: "公开页面最新观测", en: "Latest observation on the public page" },
    },
    {
      id: "energy-index",
      name: { zh: "能源商品指数月变动", en: "Energy commodity index monthly change" },
      value: -17.7,
      unit: "% MoM",
      change: -17.7,
      effectiveDate: "2026-06",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://www.worldbank.org/en/research/commodity-markets",
      note: { zh: "2026年6月环比", en: "June 2026 month over month" },
    },
    {
      id: "metals-index",
      name: { zh: "金属与矿物指数月变动", en: "Metals & minerals index monthly change" },
      value: -2.4,
      unit: "% MoM",
      change: -2.4,
      effectiveDate: "2026-06",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://www.worldbank.org/en/research/commodity-markets",
      note: { zh: "2026年6月环比", en: "June 2026 month over month" },
    },
    {
      id: "precious-index",
      name: { zh: "贵金属指数月变动", en: "Precious metals index monthly change" },
      value: -9.2,
      unit: "% MoM",
      change: -9.2,
      effectiveDate: "2026-06",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://www.worldbank.org/en/research/commodity-markets",
      note: { zh: "2026年6月环比", en: "June 2026 month over month" },
    },
  ],
  tradeSignals: [
    {
      id: "critical-mineral-controls",
      hs: "Multiple HS codes",
      material: { zh: "关键矿物", en: "Critical minerals" },
      origin: { zh: "中国", en: "China" },
      destination: { zh: "全球", en: "Global" },
      signal: { zh: "自2023年以来，受出口管制的矿产品税则号数量增至三倍", en: "Mineral tariff lines under export control have tripled since 2023" },
      effectiveDate: "2026-07-16",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "IEA",
      sourceUrl: "https://www.iea.org/reports/global-critical-minerals-outlook-2026/executive-summary",
    },
    {
      id: "refining-concentration",
      hs: "Multiple HS codes",
      material: { zh: "关键矿物精炼", en: "Critical-mineral refining" },
      origin: { zh: "最大精炼国", en: "Top refining country" },
      destination: { zh: "全球制造业", en: "Global manufacturing" },
      signal: { zh: "除稀土外，2025年最大精炼国的平均份额为72%", en: "The top refining country held a 72% average share in 2025, excluding rare earths" },
      effectiveDate: "2025",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "IEA",
      sourceUrl: "https://www.iea.org/reports/global-critical-minerals-outlook-2026/executive-summary",
    },
  ],
  freight: {
    reportDate: "2026-07-29",
    source: "Freightos",
    sourceUrl: "https://www.freightos.com/freight-resources/freight-rate-update-for-july-29th-july-29-2026-update/",
    lanes: [
      { id: "fbx01", name: { zh: "亚洲—美西", en: "Asia–US West Coast" }, value: 6212, unit: "USD/FEU", change: -12, effectiveDate: "2026-07-29", source: "Freightos FBX", sourceUrl: "https://www.freightos.com/freight-resources/freight-rate-update-for-july-29th-july-29-2026-update/" },
      { id: "fbx03", name: { zh: "亚洲—美东", en: "Asia–US East Coast" }, value: 9002, unit: "USD/FEU", change: -1, effectiveDate: "2026-07-29", source: "Freightos FBX", sourceUrl: "https://www.freightos.com/freight-resources/freight-rate-update-for-july-29th-july-29-2026-update/" },
      { id: "fbx11", name: { zh: "亚洲—北欧", en: "Asia–North Europe" }, value: 5575, unit: "USD/FEU", change: -3, effectiveDate: "2026-07-29", source: "Freightos FBX", sourceUrl: "https://www.freightos.com/freight-resources/freight-rate-update-for-july-29th-july-29-2026-update/" },
      { id: "fbx13", name: { zh: "亚洲—地中海", en: "Asia–Mediterranean" }, value: 6697, unit: "USD/FEU", change: -2, effectiveDate: "2026-07-29", source: "Freightos FBX", sourceUrl: "https://www.freightos.com/freight-resources/freight-rate-update-for-july-29th-july-29-2026-update/" },
    ],
  },
  news: [
    {
      id: "iea-critical-minerals-2026",
      publishedAt: "2026-07-16",
      source: "IEA",
      sourceUrl: "https://www.iea.org/news/supply-concentration-export-restrictions-and-declining-investment-put-critical-mineral-security-at-risk",
      tags: ["casting", "precious-metal", "stamping", "machining", "cable-wire", "connectors", "busbar", "metal-fab", "heatsink", "fans-blowers", "transformer", "power-supply", "passive", "circuit-breaker", "relay", "fasteners"],
      title: { zh: "关键矿物供应集中、出口限制与投资放缓加剧供应风险", en: "Supply concentration, export controls and slower investment raise critical-mineral risk" },
      summary: { zh: "IEA指出精炼集中度依然很高，铜到2035年的潜在供应缺口达25%，电气、金属加工与散热类品类应加强材料替代和多源认证。", en: "The IEA says refining remains highly concentrated and copper faces a potential 25% supply gap by 2035, strengthening the case for substitution and multi-sourcing across electrical, metalworking and thermal categories." },
      impact: { zh: "中长期上行风险", en: "Medium- to long-term upside risk" },
    },
    {
      id: "pcb-people-h1-2026",
      publishedAt: "2026-07-08",
      source: "PCB People",
      sourceUrl: "https://www.allelectronicsindustry.com/features/pcb-people-reports-record-breaking-first-half-as-pcb-supply-chain-pressure-intensifies/",
      tags: ["pcb", "connectors", "passive", "power-supply"],
      title: { zh: "人工智能需求推动高端印刷电路板，上游材料压力延续", en: "AI demand lifts advanced PCBs while upstream material pressure persists" },
      summary: { zh: "高速覆铜板与高层板需求增强，原材料和连续供货能力仍是2026年下半年的主要约束。", en: "Demand for high-speed laminates and high-layer-count boards is strengthening, while materials and continuity of supply remain key constraints for the second half of 2026." },
      impact: { zh: "高端板偏紧", en: "Tighter advanced-board supply" },
    },
    {
      id: "iea-grid-components",
      publishedAt: "2025-02-25",
      source: "IEA",
      sourceUrl: "https://www.iea.org/news/rising-component-prices-and-supply-chain-pressures-are-hindering-the-development-of-transmission-grid-infrastructure",
      tags: ["cable-wire", "transformer", "busbar", "connectors", "circuit-breaker", "relay", "power-supply"],
      title: { zh: "电网部件价格与交期压力持续影响扩建进度", en: "Grid-component prices and lead-time pressure continue to hinder expansion" },
      summary: { zh: "IEA公开资料显示电缆典型交期为2–3年，大型变压器最长4年，部分直流电缆超过5年；这是该专题目前可公开核验的最新发布。", en: "The latest publicly verifiable IEA release for this topic reports typical cable lead times of 2–3 years, up to four years for large transformers, and more than five years for some DC cables." },
      impact: { zh: "最新公开专题；长期偏紧", en: "Latest public topic release; structurally tight" },
    },
    {
      id: "semi-equipment-2026",
      publishedAt: "2026-07-14",
      source: "SEMI",
      sourceUrl: "https://www.semi.org/en/news-media-press/semi-press-releases/press-archive",
      tags: ["machining", "metal-fab", "fans-blowers", "heatsink", "labels", "fasteners", "connectors"],
      title: { zh: "半导体设备销售预计在2028年达到2290亿美元纪录", en: "Semiconductor equipment sales are forecast to reach a record $229 billion in 2028" },
      summary: { zh: "先进制造资本开支支持精密机加工、钣金、热管理和互连部件需求，但供应商需区分设备周期与通用工业需求。", en: "Advanced-manufacturing capital expenditure supports precision machining, sheet metal, thermal management and interconnect demand, though suppliers should distinguish the equipment cycle from broader industrial demand." },
      impact: { zh: "设备链需求支撑", en: "Supportive equipment-chain demand" },
    },
    {
      id: "plastics-resin-july-2026",
      publishedAt: "2026-07-02",
      source: "Malaysian Plastics Manufacturers Association",
      sourceUrl: "https://mpma.org.my/plastics-newsroom/resin-price-surge-raises-profit-forecasts",
      tags: ["plastics", "labels"],
      title: { zh: "树脂价格波动提高塑料制品成本与库存管理难度", en: "Resin price volatility raises cost and inventory-management pressure for plastics" },
      summary: { zh: "公开行业信息显示原料库存与补库预期可能快速传导至树脂报价，采购应同步跟踪石化原料与区域库存。", en: "Public industry reporting indicates that feedstock inventories and restocking expectations can transmit quickly into resin quotes, making petrochemical inputs and regional stocks important procurement signals." },
      impact: { zh: "短期成本波动", en: "Near-term cost volatility" },
    },
    {
      id: "gartner-ai-scaling-2026",
      publishedAt: "2026-04-29",
      source: "Gartner",
      sourceUrl: "https://www.gartner.com/en/newsroom/press-releases/2026-04-29-gartner-survey-finds-technology-integration-and-talent-perceived-as-key-roadblocks-to-scaling-ai-in-supply-chain",
      tags: ["pcb", "casting", "precious-metal", "stamping", "machining", "cable-wire", "connectors", "busbar", "metal-fab", "plastics", "heatsink", "fans-blowers", "transformer", "power-supply", "passive", "circuit-breaker", "relay", "labels", "fasteners"],
      title: { zh: "技术集成与人才缺口阻碍供应链人工智能规模化", en: "Technology integration and talent gaps hinder AI scaling in supply chains" },
      summary: { zh: "Gartner调查中，56%的受访者将旧系统集成列为障碍，50%指出人才差距；跨品类风险监测仍需可追溯的数据治理。", en: "In Gartner's survey, 56% cited legacy-system integration and 50% cited talent gaps; traceable data governance remains essential for cross-category risk monitoring." },
      impact: { zh: "运营与数据治理风险", en: "Operating and data-governance risk" },
    },
  ],
  risks: [
    {
      id: "critical-mineral-concentration",
      title: { zh: "关键矿物精炼集中", en: "Critical-mineral refining concentration" },
      summary: { zh: "镓、磁性稀土、钇、石墨、钨、碲、钴与锗的供应暴露最高。", en: "Gallium, magnet rare earths, yttrium, graphite, tungsten, tellurium, cobalt and germanium show the highest exposure." },
      effectiveDate: "2026-07-16",
      source: "IEA",
      sourceUrl: "https://www.iea.org/reports/global-critical-minerals-outlook-2026/executive-summary",
      direction: "up",
      impactWindow: { zh: "6–18个月", en: "6–18 months" },
    },
    {
      id: "grid-component-lead-times",
      title: { zh: "电网部件长交期", en: "Long grid-component lead times" },
      summary: { zh: "大型变压器和高压电缆仍需提前锁定产能；该专题沿用最新公开发布。", en: "Large transformers and high-voltage cables still require early capacity reservations; this uses the latest public topic release." },
      effectiveDate: "2025-02-25",
      source: "IEA",
      sourceUrl: "https://www.iea.org/news/rising-component-prices-and-supply-chain-pressures-are-hindering-the-development-of-transmission-grid-infrastructure",
      direction: "high",
      impactWindow: { zh: "2–5年交期", en: "2–5 year lead times" },
    },
  ],
  materials: {
    copper: {
      id: "copper",
      name: { zh: "铜", en: "Copper" },
      unit: "USD/mt",
      color: "#0f7d8c",
      lastActual: "2026-06",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://www.worldbank.org/en/research/commodity-markets",
      actual: [
        { month: "2025-12", value: 11785 }, { month: "2026-01", value: 13012 },
        { month: "2026-02", value: 12951 }, { month: "2026-03", value: 12529 },
        { month: "2026-04", value: 12951 }, { month: "2026-05", value: 13543 },
        { month: "2026-06", value: 13552 },
      ],
      forecast: [
        { month: "2026-07", value: 13590 }, { month: "2026-08", value: 13630 },
        { month: "2026-09", value: 13670 }, { month: "2026-10", value: 13710 },
        { month: "2026-11", value: 13750 }, { month: "2026-12", value: 13790 },
        { month: "2027-01", value: 13830 }, { month: "2027-02", value: 13870 },
        { month: "2027-03", value: 13910 }, { month: "2027-04", value: 13950 },
        { month: "2027-05", value: 13990 }, { month: "2027-06", value: 14030 },
      ],
      forecastGeneratedAt: "2026-07-30",
      assumptions: { zh: "编辑基准情景：供应集中和电网需求提供支撑，不代表世界银行预测。", en: "Editorial baseline scenario: supply concentration and grid demand provide support; this is not a World Bank forecast." },
    },
    aluminum: {
      id: "aluminum",
      name: { zh: "铝", en: "Aluminum" },
      unit: "USD/mt",
      color: "#d18b31",
      lastActual: "2026-06",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://www.worldbank.org/en/research/commodity-markets",
      actual: [
        { month: "2025-12", value: 2876 }, { month: "2026-01", value: 3142 },
        { month: "2026-02", value: 3065 }, { month: "2026-03", value: 3373 },
        { month: "2026-04", value: 3600 }, { month: "2026-05", value: 3666 },
        { month: "2026-06", value: 3439 },
      ],
      forecast: [
        { month: "2026-07", value: 3445 }, { month: "2026-08", value: 3450 },
        { month: "2026-09", value: 3455 }, { month: "2026-10", value: 3460 },
        { month: "2026-11", value: 3465 }, { month: "2026-12", value: 3470 },
        { month: "2027-01", value: 3475 }, { month: "2027-02", value: 3480 },
        { month: "2027-03", value: 3485 }, { month: "2027-04", value: 3490 },
        { month: "2027-05", value: 3495 }, { month: "2027-06", value: 3500 },
      ],
      forecastGeneratedAt: "2026-07-30",
      assumptions: { zh: "编辑基准情景：能源成本与产能增长大致抵消，不代表世界银行预测。", en: "Editorial baseline scenario: energy costs and capacity growth broadly offset; this is not a World Bank forecast." },
    },
    gold: {
      id: "gold",
      name: { zh: "黄金", en: "Gold" },
      unit: "USD/troy oz",
      color: "#b39536",
      lastActual: "2026-06",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://www.worldbank.org/en/research/commodity-markets",
      actual: [
        { month: "2025-12", value: 4309 }, { month: "2026-01", value: 4753 },
        { month: "2026-02", value: 5020 }, { month: "2026-03", value: 4856 },
        { month: "2026-04", value: 4721 }, { month: "2026-05", value: 4587 },
        { month: "2026-06", value: 4228 },
      ],
      forecast: [
        { month: "2026-07", value: 4240 }, { month: "2026-08", value: 4255 },
        { month: "2026-09", value: 4270 }, { month: "2026-10", value: 4285 },
        { month: "2026-11", value: 4300 }, { month: "2026-12", value: 4315 },
        { month: "2027-01", value: 4330 }, { month: "2027-02", value: 4345 },
        { month: "2027-03", value: 4360 }, { month: "2027-04", value: 4375 },
        { month: "2027-05", value: 4390 }, { month: "2027-06", value: 4405 },
      ],
      forecastGeneratedAt: "2026-07-30",
      assumptions: { zh: "编辑基准情景：避险需求与高位回调风险并存，不代表世界银行预测。", en: "Editorial baseline scenario: safe-haven demand coexists with correction risk; this is not a World Bank forecast." },
    },
    silver: {
      id: "silver",
      name: { zh: "白银", en: "Silver" },
      unit: "USD/troy oz",
      color: "#6b7b89",
      lastActual: "2026-06",
      verifiedAt: "2026-07-30T08:30:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://www.worldbank.org/en/research/commodity-markets",
      actual: [
        { month: "2025-12", value: 62.3 }, { month: "2026-01", value: 92.1 },
        { month: "2026-02", value: 81.9 }, { month: "2026-03", value: 77.9 },
        { month: "2026-04", value: 75.9 }, { month: "2026-05", value: 78.0 },
        { month: "2026-06", value: 66.7 },
      ],
      forecast: [
        { month: "2026-07", value: 67.0 }, { month: "2026-08", value: 67.3 },
        { month: "2026-09", value: 67.6 }, { month: "2026-10", value: 67.9 },
        { month: "2026-11", value: 68.2 }, { month: "2026-12", value: 68.5 },
        { month: "2027-01", value: 68.8 }, { month: "2027-02", value: 69.1 },
        { month: "2027-03", value: 69.4 }, { month: "2027-04", value: 69.7 },
        { month: "2027-05", value: 70.0 }, { month: "2027-06", value: 70.3 },
      ],
      forecastGeneratedAt: "2026-07-30",
      assumptions: { zh: "编辑基准情景：工业与贵金属需求温和恢复，不代表世界银行预测。", en: "Editorial baseline scenario: industrial and precious-metal demand recover gradually; this is not a World Bank forecast." },
    },
  },
  sources: [
    { id: "eia", name: "U.S. EIA", effectiveDate: "2026-07-20", verifiedAt: "2026-07-30T08:30:00+08:00", url: "https://www.eia.gov/dnav/pet/hist/RBRTED.htm" },
    { id: "world-bank", name: "World Bank Commodity Markets", effectiveDate: "2026-06", verifiedAt: "2026-07-30T08:30:00+08:00", url: "https://www.worldbank.org/en/research/commodity-markets" },
    { id: "freightos", name: "Freightos FBX", effectiveDate: "2026-07-29", verifiedAt: "2026-07-30T08:30:00+08:00", url: "https://www.freightos.com/freight-resources/freight-rate-update-for-july-29th-july-29-2026-update/" },
    { id: "iea", name: "IEA", effectiveDate: "2026-07-16", verifiedAt: "2026-07-30T08:30:00+08:00", url: "https://www.iea.org/reports/global-critical-minerals-outlook-2026/executive-summary" },
    { id: "gartner", name: "Gartner", effectiveDate: "2026-04-29", verifiedAt: "2026-07-30T08:30:00+08:00", url: "https://www.gartner.com/en/newsroom/topics/supply-chain" },
    { id: "semi", name: "SEMI", effectiveDate: "2026-07-14", verifiedAt: "2026-07-30T08:30:00+08:00", url: "https://www.semi.org/en/news-media-press/semi-press-releases/press-archive" },
  ],
};
