window.SUPPLY_DATA = {
  verifiedAt: "2026-09-10T07:00:00+08:00",
  markets: [
    {
      id: "brent",
      name: { zh: "布伦特原油现货周均价", en: "Brent spot crude weekly average" },
      value: 89.73,
      unit: "USD/bbl",
      change: null,
      effectiveDate: "2026-08-28",
      verifiedAt: "2026-09-03T07:00:00+08:00",
      source: "U.S. EIA",
      sourceUrl: "https://www.eia.gov/dnav/pet/pet_pri_spt_s1_w.htm",
      note: { zh: "截至2026年8月28日的周均价", en: "Weekly average through August 28, 2026" },
    },
    {
      id: "energy-index",
      name: { zh: "能源商品指数月变动", en: "Energy commodity index monthly change" },
      value: 8.8,
      unit: "% MoM",
      change: 8.8,
      effectiveDate: "2026-08",
      verifiedAt: "2026-09-03T07:00:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Pink-Sheet-September-2026.pdf",
      note: { zh: "2026年8月环比", en: "August 2026 month over month" },
    },
    {
      id: "metals-index",
      name: { zh: "金属与矿物指数月变动", en: "Metals & minerals index monthly change" },
      value: 4.1,
      unit: "% MoM",
      change: 4.1,
      effectiveDate: "2026-08",
      verifiedAt: "2026-09-03T07:00:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Pink-Sheet-September-2026.pdf",
      note: { zh: "2026年8月环比", en: "August 2026 month over month" },
    },
    {
      id: "precious-index",
      name: { zh: "贵金属指数月变动", en: "Precious metals index monthly change" },
      value: 8.8,
      unit: "% MoM",
      change: 8.8,
      effectiveDate: "2026-08",
      verifiedAt: "2026-09-03T07:00:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Pink-Sheet-September-2026.pdf",
      note: { zh: "2026年8月环比", en: "August 2026 month over month" },
    },
  ],
  tradeSignals: [
    {
      id: "critical-mineral-controls",
      hs: "Multiple HS codes",
      material: { zh: "关键矿物", en: "Critical minerals" },
      origin: { zh: "中国", en: "China" },
      destination: { zh: "全球", en: "Global" },
      signal: { zh: "自2023年以来，受出口管制的矿产品税则号数量增至三倍", en: "Mineral tariff lines under export control have tripled since 2023" },
      effectiveDate: "2026-07-16",
      verifiedAt: "2026-08-24T07:00:00+08:00",
      source: "IEA",
      sourceUrl: "https://www.iea.org/reports/global-critical-minerals-outlook-2026/executive-summary",
    },
    {
      id: "refining-concentration",
      hs: "Multiple HS codes",
      material: { zh: "关键矿物精炼", en: "Critical-mineral refining" },
      origin: { zh: "最大精炼国", en: "Top refining country" },
      destination: { zh: "全球制造业", en: "Global manufacturing" },
      signal: { zh: "除稀土外，2025年最大精炼国的平均份额为72%", en: "The top refining country held a 72% average share in 2025, excluding rare earths" },
      effectiveDate: "2025",
      verifiedAt: "2026-08-24T07:00:00+08:00",
      source: "IEA",
      sourceUrl: "https://www.iea.org/reports/global-critical-minerals-outlook-2026/executive-summary",
    },
  ],
  freight: {
    reportDate: "2026-09-02",
    source: "Freightos",
    sourceUrl: "https://www.freightos.com/freight-resources/typhoon-disruptions-driving-congestion-and-putting-pressure-on-rates-september-25-2026-update/",
    lanes: [
      { id: "fbx01", name: { zh: "亚洲—美西", en: "Asia–US West Coast" }, value: 7600, unit: "USD/FEU approx.", change: 2, effectiveDate: "2026-09-02", source: "Freightos FBX", sourceUrl: "https://www.freightos.com/freight-resources/typhoon-disruptions-driving-congestion-and-putting-pressure-on-rates-september-25-2026-update/" },
      { id: "fbx03", name: { zh: "亚洲—美东", en: "Asia–US East Coast" }, value: 9800, unit: "USD/FEU approx.", change: 2, effectiveDate: "2026-09-02", source: "Freightos FBX", sourceUrl: "https://www.freightos.com/freight-resources/typhoon-disruptions-driving-congestion-and-putting-pressure-on-rates-september-25-2026-update/" },
      { id: "fbx11", name: { zh: "亚洲—北欧", en: "Asia–North Europe" }, value: 4600, unit: "USD/FEU approx.", change: -1, effectiveDate: "2026-09-02", source: "Freightos FBX", sourceUrl: "https://www.freightos.com/freight-resources/typhoon-disruptions-driving-congestion-and-putting-pressure-on-rates-september-25-2026-update/" },
      { id: "fbx13", name: { zh: "亚洲—地中海", en: "Asia–Mediterranean" }, value: 4800, unit: "USD/FEU approx.", change: -4, effectiveDate: "2026-09-02", source: "Freightos FBX", sourceUrl: "https://www.freightos.com/freight-resources/typhoon-disruptions-driving-congestion-and-putting-pressure-on-rates-september-25-2026-update/" },
    ],
  },
  news: [
    {
      id: "semi-eu-chips-act-2-2026",
      publishedAt: "2026-09-08",
      source: "SEMI Europe",
      sourceUrl: "https://www.semi.org/en/semi-press-release/semi-calls-on-the-chips-act-2.0-to-strengthen-semiconductor-competitiveness-and-resilience",
      tags: ["pcb", "machining", "connectors", "metal-fab", "heatsink", "fans-blowers", "power-supply", "passive", "relay"],
      title: { zh: "SEMI建议欧盟Chips Act 2.0覆盖完整半导体供应链", en: "SEMI urges EU Chips Act 2.0 support across the semiconductor value chain" },
      summary: { zh: "SEMI Europe提出九项政策建议，主张将支持范围扩展至设计、材料、设备、制造和先进封装，并加快投资与许可流程、建立行业主导的安全供应链监测。该文件是行业协会建议，并非已生效法规。", en: "SEMI Europe issued nine policy recommendations calling for support across design, materials, equipment, manufacturing and advanced packaging, faster investment and permitting, and secure industry-led supply-chain monitoring. The position paper is an industry recommendation, not enacted law." },
      impact: { zh: "欧洲半导体投资与供应链政策信号", en: "European semiconductor investment and policy signal" },
    },
    {
      id: "foley-grid-materials-2026",
      publishedAt: "2026-09-03",
      source: "Foley & Lardner / CoBank",
      sourceUrl: "https://www.foley.com/insights/publications/2026/09/the-grids-bottleneck-isnt-just-money-its-materials/",
      tags: ["cable-wire", "transformer", "busbar", "connectors", "circuit-breaker", "relay", "metal-fab"],
      title: { zh: "电网扩张仍受变压器、导线与开关设备供给约束", en: "Grid expansion remains constrained by transformers, conductors and switchgear" },
      summary: { zh: "公开行业分析援引CoBank与Wood Mackenzie资料指出，需求超过关键材料和设备供应，部分设备交期达到三至四年；历史调查中的电力变压器平均交期为128周，需注意这些交期数据早于文章发布日期。", en: "Public industry analysis citing CoBank and Wood Mackenzie says demand continues to exceed critical-material and equipment supply, with some equipment carrying three- to four-year lead times; the cited 128-week average for power transformers comes from an earlier survey and should not be read as a September spot quote." },
      impact: { zh: "电网设备排产与材料风险", en: "Grid-equipment scheduling and material risk" },
    },
    {
      id: "pcim-wuerth-pcb-materials-2026",
      publishedAt: "2026-08-28",
      source: "PCIM / Würth Elektronik",
      sourceUrl: "https://news.pcim.mesago.com/ai-boom-intensifies-pcb-material-shortages-a-69f95c3078045acfbb7868f4d872fbb4/",
      tags: ["pcb", "connectors", "power-supply", "passive"],
      title: { zh: "人工智能需求加剧印刷电路板基础材料短缺", en: "AI demand intensifies PCB base-material shortages" },
      summary: { zh: "Würth Elektronik称，人工智能服务器用板层数通常为传统设计的三至五倍，覆铜板、铜箔、半固化片、高性能树脂及钻铣刀具材料均承压；玻纤布供应紧张预计在2028年前难以明显缓解。", en: "Würth Elektronik says AI-server boards typically use three to five times as many layers as conventional designs, pressuring copper-clad laminates, copper foil, prepregs, high-performance resins and tooling materials; fiberglass-fabric constraints may not ease materially before 2028." },
      impact: { zh: "材料配额、涨价与交期延长风险", en: "Allocation, price and lead-time risk" },
    },
    {
      id: "freightos-typhoon-congestion-2026",
      publishedAt: "2026-09-02",
      source: "Freightos",
      sourceUrl: "https://www.freightos.com/freight-resources/typhoon-disruptions-driving-congestion-and-putting-pressure-on-rates-september-25-2026-update/",
      tags: ["pcb", "cable-wire", "connectors", "metal-fab", "plastics", "transformer", "power-supply"],
      title: { zh: "台风与亚洲港口拥堵推高跨太平洋运价", en: "Typhoons and Asian port congestion lift transpacific rates" },
      summary: { zh: "Freightos称亚美西岸和东岸周度价格均上涨2%，分别超过约7,600与9,800美元/FEU；北欧与地中海航线随需求降温回落，但远东港口拥堵仍支撑运价。", en: "Freightos reports 2% weekly gains on both transpacific coasts, to above roughly $7,600/FEU and about $9,800/FEU; North Europe and Mediterranean lanes eased with cooling demand, though Far East port congestion continues to support rates." },
      impact: { zh: "跨太平洋到岸成本偏强", en: "Firm transpacific landed costs" },
    },
    {
      id: "evertiq-pcb-fr4-2026",
      publishedAt: "2026-08-19",
      source: "Evertiq / Confidee",
      sourceUrl: "https://evertiq.com/news/2026-08-19-pcb-material-shortage-spreads-to-standard-fr-4-as-structural-shift-deepens",
      tags: ["pcb", "connectors", "power-supply", "passive"],
      title: { zh: "印刷电路板材料短缺从高端覆铜板扩散至标准FR-4", en: "PCB material shortage spreads from advanced laminates to standard FR-4" },
      summary: { zh: "行业更新显示，玻纤布、树脂和铜箔同时承压，标准FR-4和厚铜覆铜板交期开始延长，供应紧张预计延续至2027年。", en: "An industry update says simultaneous pressure on glass cloth, resin and copper foil is extending lead times for standard FR-4 and thick copper-clad laminates, with tightness expected into 2027." },
      impact: { zh: "常规板交期上行", en: "Standard-board lead times rising" },
    },
    {
      id: "iea-critical-minerals-2026",
      publishedAt: "2026-07-16",
      source: "IEA",
      sourceUrl: "https://www.iea.org/news/supply-concentration-export-restrictions-and-declining-investment-put-critical-mineral-security-at-risk",
      tags: ["casting", "precious-metal", "stamping", "machining", "cable-wire", "connectors", "busbar", "metal-fab", "heatsink", "fans-blowers", "transformer", "power-supply", "passive", "circuit-breaker", "relay", "fasteners"],
      title: { zh: "关键矿物供应集中、出口限制与投资放缓加剧供应风险", en: "Supply concentration, export controls and slower investment raise critical-mineral risk" },
      summary: { zh: "IEA指出精炼集中度依然很高，铜到2035年的潜在供应缺口达25%，电气、金属加工与散热类品类应加强材料替代和多源认证。", en: "The IEA says refining remains highly concentrated and copper faces a potential 25% supply gap by 2035, strengthening the case for substitution and multi-sourcing across electrical, metalworking and thermal categories." },
      impact: { zh: "中长期上行风险", en: "Medium- to long-term upside risk" },
    },
    {
      id: "pcb-people-h1-2026",
      publishedAt: "2026-07-08",
      source: "PCB People",
      sourceUrl: "https://www.allelectronicsindustry.com/features/pcb-people-reports-record-breaking-first-half-as-pcb-supply-chain-pressure-intensifies/",
      tags: ["pcb", "connectors", "passive", "power-supply"],
      title: { zh: "人工智能需求推动高端印刷电路板，上游材料压力延续", en: "AI demand lifts advanced PCBs while upstream material pressure persists" },
      summary: { zh: "高速覆铜板与高层板需求增强，原材料和连续供货能力仍是2026年下半年的主要约束。", en: "Demand for high-speed laminates and high-layer-count boards is strengthening, while materials and continuity of supply remain key constraints for the second half of 2026." },
      impact: { zh: "高端板偏紧", en: "Tighter advanced-board supply" },
    },
    {
      id: "iea-grid-components",
      publishedAt: "2025-02-25",
      source: "IEA",
      sourceUrl: "https://www.iea.org/news/rising-component-prices-and-supply-chain-pressures-are-hindering-the-development-of-transmission-grid-infrastructure",
      tags: ["cable-wire", "transformer", "busbar", "connectors", "circuit-breaker", "relay", "power-supply"],
      title: { zh: "电网部件价格与交期压力持续影响扩建进度", en: "Grid-component prices and lead-time pressure continue to hinder expansion" },
      summary: { zh: "IEA公开资料显示电缆典型交期为2–3年，大型变压器最长4年，部分直流电缆超过5年；这是该专题目前可公开核验的最新发布。", en: "The latest publicly verifiable IEA release for this topic reports typical cable lead times of 2–3 years, up to four years for large transformers, and more than five years for some DC cables." },
      impact: { zh: "最新公开专题；长期偏紧", en: "Latest public topic release; structurally tight" },
    },
    {
      id: "semi-equipment-2026",
      publishedAt: "2026-07-14",
      source: "SEMI",
      sourceUrl: "https://www.semi.org/en/news-media-press/semi-press-releases/press-archive",
      tags: ["machining", "metal-fab", "fans-blowers", "heatsink", "labels", "fasteners", "connectors"],
      title: { zh: "半导体设备销售预计在2028年达到2290亿美元纪录", en: "Semiconductor equipment sales are forecast to reach a record $229 billion in 2028" },
      summary: { zh: "先进制造资本开支支持精密机加工、钣金、热管理和互连部件需求，但供应商需区分设备周期与通用工业需求。", en: "Advanced-manufacturing capital expenditure supports precision machining, sheet metal, thermal management and interconnect demand, though suppliers should distinguish the equipment cycle from broader industrial demand." },
      impact: { zh: "设备链需求支撑", en: "Supportive equipment-chain demand" },
    },
    {
      id: "plastics-resin-july-2026",
      publishedAt: "2026-07-02",
      source: "Malaysian Plastics Manufacturers Association",
      sourceUrl: "https://mpma.org.my/plastics-newsroom/resin-price-surge-raises-profit-forecasts",
      tags: ["plastics", "labels"],
      title: { zh: "树脂价格波动提高塑料制品成本与库存管理难度", en: "Resin price volatility raises cost and inventory-management pressure for plastics" },
      summary: { zh: "公开行业信息显示原料库存与补库预期可能快速传导至树脂报价，采购应同步跟踪石化原料与区域库存。", en: "Public industry reporting indicates that feedstock inventories and restocking expectations can transmit quickly into resin quotes, making petrochemical inputs and regional stocks important procurement signals." },
      impact: { zh: "短期成本波动", en: "Near-term cost volatility" },
    },
    {
      id: "gartner-ai-scaling-2026",
      publishedAt: "2026-04-29",
      source: "Gartner",
      sourceUrl: "https://www.gartner.com/en/newsroom/press-releases/2026-04-29-gartner-survey-finds-technology-integration-and-talent-perceived-as-key-roadblocks-to-scaling-ai-in-supply-chain",
      tags: ["pcb", "casting", "precious-metal", "stamping", "machining", "cable-wire", "connectors", "busbar", "metal-fab", "plastics", "heatsink", "fans-blowers", "transformer", "power-supply", "passive", "circuit-breaker", "relay", "labels", "fasteners"],
      title: { zh: "技术集成与人才缺口阻碍供应链人工智能规模化", en: "Technology integration and talent gaps hinder AI scaling in supply chains" },
      summary: { zh: "Gartner调查中，56%的受访者将旧系统集成列为障碍，50%指出人才差距；跨品类风险监测仍需可追溯的数据治理。", en: "In Gartner's survey, 56% cited legacy-system integration and 50% cited talent gaps; traceable data governance remains essential for cross-category risk monitoring." },
      impact: { zh: "运营与数据治理风险", en: "Operating and data-governance risk" },
    },
  ],
  risks: [
    {
      id: "critical-mineral-concentration",
      title: { zh: "关键矿物精炼集中", en: "Critical-mineral refining concentration" },
      summary: { zh: "镓、磁性稀土、钇、石墨、钨、碲、钴与锗的供应暴露最高。", en: "Gallium, magnet rare earths, yttrium, graphite, tungsten, tellurium, cobalt and germanium show the highest exposure." },
      effectiveDate: "2026-07-16",
      source: "IEA",
      sourceUrl: "https://www.iea.org/reports/global-critical-minerals-outlook-2026/executive-summary",
      direction: "up",
      impactWindow: { zh: "6–18个月", en: "6–18 months" },
    },
    {
      id: "grid-component-lead-times",
      title: { zh: "电网部件长交期", en: "Long grid-component lead times" },
      summary: { zh: "大型变压器和高压电缆仍需提前锁定产能；该专题沿用最新公开发布。", en: "Large transformers and high-voltage cables still require early capacity reservations; this uses the latest public topic release." },
      effectiveDate: "2025-02-25",
      source: "IEA",
      sourceUrl: "https://www.iea.org/news/rising-component-prices-and-supply-chain-pressures-are-hindering-the-development-of-transmission-grid-infrastructure",
      direction: "high",
      impactWindow: { zh: "2–5年交期", en: "2–5 year lead times" },
    },
  ],
  materials: {
    copper: {
      id: "copper",
      name: { zh: "铜", en: "Copper" },
      unit: "USD/mt",
      color: "#0f7d8c",
      lastActual: "2026-08",
      verifiedAt: "2026-09-03T07:00:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Pink-Sheet-September-2026.pdf",
      actual: [
        { month: "2025-12", value: 11785 }, { month: "2026-01", value: 13012 },
        { month: "2026-02", value: 12951 }, { month: "2026-03", value: 12529 },
        { month: "2026-04", value: 12951 }, { month: "2026-05", value: 13543 },
        { month: "2026-06", value: 13552 }, { month: "2026-07", value: 13543 },
        { month: "2026-08", value: 14326 },
      ],
      forecast: [
        { month: "2026-09", value: 14340 }, { month: "2026-10", value: 14370 },
        { month: "2026-11", value: 14400 }, { month: "2026-12", value: 14430 },
        { month: "2027-01", value: 14460 }, { month: "2027-02", value: 14490 },
        { month: "2027-03", value: 14520 }, { month: "2027-04", value: 14550 },
        { month: "2027-05", value: 14580 }, { month: "2027-06", value: 14610 },
        { month: "2027-07", value: 14640 }, { month: "2027-08", value: 14670 },
      ],
      forecastGeneratedAt: "2026-09-03",
      assumptions: { zh: "编辑基准情景：供应集中和电网需求提供支撑，不代表世界银行预测。", en: "Editorial baseline scenario: supply concentration and grid demand provide support; this is not a World Bank forecast." },
    },
    aluminum: {
      id: "aluminum",
      name: { zh: "铝", en: "Aluminum" },
      unit: "USD/mt",
      color: "#d18b31",
      lastActual: "2026-08",
      verifiedAt: "2026-09-03T07:00:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Pink-Sheet-September-2026.pdf",
      actual: [
        { month: "2025-12", value: 2876 }, { month: "2026-01", value: 3142 },
        { month: "2026-02", value: 3065 }, { month: "2026-03", value: 3373 },
        { month: "2026-04", value: 3600 }, { month: "2026-05", value: 3666 },
        { month: "2026-06", value: 3439 }, { month: "2026-07", value: 3161 },
        { month: "2026-08", value: 3251 },
      ],
      forecast: [
        { month: "2026-09", value: 3260 }, { month: "2026-10", value: 3270 },
        { month: "2026-11", value: 3280 }, { month: "2026-12", value: 3290 },
        { month: "2027-01", value: 3300 }, { month: "2027-02", value: 3310 },
        { month: "2027-03", value: 3320 }, { month: "2027-04", value: 3330 },
        { month: "2027-05", value: 3340 }, { month: "2027-06", value: 3350 },
        { month: "2027-07", value: 3360 }, { month: "2027-08", value: 3370 },
      ],
      forecastGeneratedAt: "2026-09-03",
      assumptions: { zh: "编辑基准情景：能源成本与产能增长大致抵消，不代表世界银行预测。", en: "Editorial baseline scenario: energy costs and capacity growth broadly offset; this is not a World Bank forecast." },
    },
    gold: {
      id: "gold",
      name: { zh: "黄金", en: "Gold" },
      unit: "USD/troy oz",
      color: "#b39536",
      lastActual: "2026-08",
      verifiedAt: "2026-09-03T07:00:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Pink-Sheet-September-2026.pdf",
      actual: [
        { month: "2025-12", value: 4309 }, { month: "2026-01", value: 4753 },
        { month: "2026-02", value: 5020 }, { month: "2026-03", value: 4856 },
        { month: "2026-04", value: 4721 }, { month: "2026-05", value: 4587 },
        { month: "2026-06", value: 4228 }, { month: "2026-07", value: 4073 },
        { month: "2026-08", value: 4411 },
      ],
      forecast: [
        { month: "2026-09", value: 4425 }, { month: "2026-10", value: 4440 },
        { month: "2026-11", value: 4455 }, { month: "2026-12", value: 4470 },
        { month: "2027-01", value: 4485 }, { month: "2027-02", value: 4500 },
        { month: "2027-03", value: 4515 }, { month: "2027-04", value: 4530 },
        { month: "2027-05", value: 4545 }, { month: "2027-06", value: 4560 },
        { month: "2027-07", value: 4575 }, { month: "2027-08", value: 4590 },
      ],
      forecastGeneratedAt: "2026-09-03",
      assumptions: { zh: "编辑基准情景：避险需求与高位回调风险并存，不代表世界银行预测。", en: "Editorial baseline scenario: safe-haven demand coexists with correction risk; this is not a World Bank forecast." },
    },
    silver: {
      id: "silver",
      name: { zh: "白银", en: "Silver" },
      unit: "USD/troy oz",
      color: "#6b7b89",
      lastActual: "2026-08",
      verifiedAt: "2026-09-03T07:00:00+08:00",
      source: "World Bank Commodity Markets",
      sourceUrl: "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Pink-Sheet-September-2026.pdf",
      actual: [
        { month: "2025-12", value: 62.3 }, { month: "2026-01", value: 92.1 },
        { month: "2026-02", value: 81.9 }, { month: "2026-03", value: 77.9 },
        { month: "2026-04", value: 75.9 }, { month: "2026-05", value: 78.0 },
        { month: "2026-06", value: 66.7 }, { month: "2026-07", value: 58.8 },
        { month: "2026-08", value: 65.4 },
      ],
      forecast: [
        { month: "2026-09", value: 65.6 }, { month: "2026-10", value: 65.9 },
        { month: "2026-11", value: 66.2 }, { month: "2026-12", value: 66.5 },
        { month: "2027-01", value: 66.8 }, { month: "2027-02", value: 67.1 },
        { month: "2027-03", value: 67.4 }, { month: "2027-04", value: 67.7 },
        { month: "2027-05", value: 68.0 }, { month: "2027-06", value: 68.3 },
        { month: "2027-07", value: 68.6 }, { month: "2027-08", value: 68.9 },
      ],
      forecastGeneratedAt: "2026-09-03",
      assumptions: { zh: "编辑基准情景：工业与贵金属需求温和恢复，不代表世界银行预测。", en: "Editorial baseline scenario: industrial and precious-metal demand recover gradually; this is not a World Bank forecast." },
    },
  },
  sources: [
    { id: "eia", name: "U.S. EIA", effectiveDate: "2026-08-28", verifiedAt: "2026-09-03T07:00:00+08:00", url: "https://www.eia.gov/dnav/pet/pet_pri_spt_s1_w.htm" },
    { id: "world-bank", name: "World Bank Commodity Markets", effectiveDate: "2026-08", verifiedAt: "2026-09-03T07:00:00+08:00", url: "https://thedocs.worldbank.org/en/doc/74e8be41ceb20fa0da750cda2f6b9e4e-0050012026/related/CMO-Pink-Sheet-September-2026.pdf" },
    { id: "freightos", name: "Freightos FBX", effectiveDate: "2026-09-02", verifiedAt: "2026-09-07T07:00:00+08:00", url: "https://www.freightos.com/freight-resources/typhoon-disruptions-driving-congestion-and-putting-pressure-on-rates-september-25-2026-update/" },
    { id: "iea", name: "IEA", effectiveDate: "2026-07-16", verifiedAt: "2026-08-24T07:00:00+08:00", url: "https://www.iea.org/reports/global-critical-minerals-outlook-2026/executive-summary" },
    { id: "gartner", name: "Gartner", effectiveDate: "2026-04-29", verifiedAt: "2026-08-24T07:00:00+08:00", url: "https://www.gartner.com/en/newsroom/topics/supply-chain" },
    { id: "semi", name: "SEMI", effectiveDate: "2026-09-08", verifiedAt: "2026-09-10T07:00:00+08:00", url: "https://www.semi.org/en/semi-press-release/semi-calls-on-the-chips-act-2.0-to-strengthen-semiconductor-competitiveness-and-resilience" },
    { id: "evertiq", name: "Evertiq / Confidee", effectiveDate: "2026-08-19", verifiedAt: "2026-08-24T07:00:00+08:00", url: "https://evertiq.com/news/2026-08-19-pcb-material-shortage-spreads-to-standard-fr-4-as-structural-shift-deepens" },
    { id: "pcim-wuerth", name: "PCIM / Würth Elektronik", effectiveDate: "2026-08-28", verifiedAt: "2026-08-31T07:00:00+08:00", url: "https://news.pcim.mesago.com/ai-boom-intensifies-pcb-material-shortages-a-69f95c3078045acfbb7868f4d872fbb4/" },
    { id: "foley-cobank", name: "Foley & Lardner / CoBank", effectiveDate: "2026-09-03", verifiedAt: "2026-09-07T07:00:00+08:00", url: "https://www.foley.com/insights/publications/2026/09/the-grids-bottleneck-isnt-just-money-its-materials/" },
  ],
};
